/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.resumebuilder;

import java.awt.Color;
import java.awt.Container;
import javax.swing.JOptionPane;

/**
 *
 * @author EdenChung
 */
public class ProjectEntryPanel extends javax.swing.JPanel {

    /**
     * Creates new form AchievementEntryPanel
     */
    public ProjectEntryPanel() {
        numProject++;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPlaceHolderProjectName = new com.mycompany.resumebuilder.JTextFieldPlaceHolder();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPlaceHolderProgrammingLanguages = new com.mycompany.resumebuilder.JTextFieldPlaceHolder();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPlaceHolderDate = new com.mycompany.resumebuilder.JTextFieldPlaceHolder();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPlaceHolderURL = new com.mycompany.resumebuilder.JTextFieldPlaceHolder();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPlaceHolderDescription = new com.mycompany.resumebuilder.JTextFieldPlaceHolder();
        emptyPlaceholder = new javax.swing.JLabel();
        deleteProject = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setMinimumSize(new java.awt.Dimension(400, 143));
        setLayout(new java.awt.GridLayout(7, 2, 0, 10));

        jLabel1.setText("Name of project*");
        add(jLabel1);

        jTextFieldPlaceHolderProjectName.setPlaceHolder("Project name");
        jTextFieldPlaceHolderProjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlaceHolderProjectNameActionPerformed(evt);
            }
        });
        add(jTextFieldPlaceHolderProjectName);

        jLabel2.setText("Programming languages/frameworks*");
        add(jLabel2);

        jTextFieldPlaceHolderProgrammingLanguages.setPlaceHolder("Programming languages");
        jTextFieldPlaceHolderProgrammingLanguages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlaceHolderProgrammingLanguagesActionPerformed(evt);
            }
        });
        add(jTextFieldPlaceHolderProgrammingLanguages);

        jLabel3.setText("Date*");
        add(jLabel3);

        jTextFieldPlaceHolderDate.setPlaceHolder("Date");
        jTextFieldPlaceHolderDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlaceHolderDateActionPerformed(evt);
            }
        });
        add(jTextFieldPlaceHolderDate);

        jLabel6.setText("URL");
        add(jLabel6);

        jTextFieldPlaceHolderURL.setPlaceHolder("URL");
        jTextFieldPlaceHolderURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlaceHolderURLActionPerformed(evt);
            }
        });
        add(jTextFieldPlaceHolderURL);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel4.setText("Description (write ** between each bullet point)");
        add(jLabel4);

        jTextFieldPlaceHolderDescription.setPlaceHolder("Description");
        jTextFieldPlaceHolderDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlaceHolderDescriptionActionPerformed(evt);
            }
        });
        add(jTextFieldPlaceHolderDescription);
        add(emptyPlaceholder);

        deleteProject.setText("Delete project");
        deleteProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProjectActionPerformed(evt);
            }
        });
        add(deleteProject);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPlaceHolderProjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceHolderProjectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceHolderProjectNameActionPerformed

    private void jTextFieldPlaceHolderProgrammingLanguagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceHolderProgrammingLanguagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceHolderProgrammingLanguagesActionPerformed

    private void jTextFieldPlaceHolderDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceHolderDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceHolderDateActionPerformed

    private void deleteProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProjectActionPerformed

        if (numProject > 1) {
            // Decrement the number of achievements when a panel is deleted
            numProject--;

            // Code to perform when the "Delete" button is clicked
            Container parent = getParent();
            parent.remove(this);
            parent.revalidate();
            parent.repaint();
        } else {
            // Show a message that deletion is not allowed if there is only one achievement
            JOptionPane.showMessageDialog(this, "You cannot delete the last experience.");
        }
    }//GEN-LAST:event_deleteProjectActionPerformed

    private void jTextFieldPlaceHolderDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceHolderDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceHolderDescriptionActionPerformed

    private void jTextFieldPlaceHolderURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceHolderURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceHolderURLActionPerformed
    public String getName() {
        return jTextFieldPlaceHolderProjectName.getText();
    }
    
    public String getProgrammingLanguages() {
        return jTextFieldPlaceHolderProgrammingLanguages.getText();
    }
    
    public String getDate() {
        return jTextFieldPlaceHolderDate.getText();
    }
    
    public String getURL() {
        return jTextFieldPlaceHolderURL.getText();
    }
    
    public String getDescription() {
        return jTextFieldPlaceHolderDescription.getText();
    }
    
    public int getNumProjects() {
        return numProject;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteProject;
    private javax.swing.JLabel emptyPlaceholder;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private com.mycompany.resumebuilder.JTextFieldPlaceHolder jTextFieldPlaceHolderDate;
    private com.mycompany.resumebuilder.JTextFieldPlaceHolder jTextFieldPlaceHolderDescription;
    private com.mycompany.resumebuilder.JTextFieldPlaceHolder jTextFieldPlaceHolderProgrammingLanguages;
    private com.mycompany.resumebuilder.JTextFieldPlaceHolder jTextFieldPlaceHolderProjectName;
    private com.mycompany.resumebuilder.JTextFieldPlaceHolder jTextFieldPlaceHolderURL;
    // End of variables declaration//GEN-END:variables

    private static int numProject = 0;
}
